// <auto-generated />
using System;
using EPortalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EPortalApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327150818_FinalFixBillNullable")]
    partial class FinalFixBillNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("EPortalApi.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUser");
                });

            modelBuilder.Entity("EPortalApi.Models.Bill", b =>
                {
                    b.Property<int>("Bill_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Bill_ID"));

                    b.Property<string>("BillType")
                        .HasColumnType("text");

                    b.Property<string>("CitizenName")
                        .HasColumnType("text");

                    b.Property<string>("ConsumerNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IDNo")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("P_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<decimal>("Total_amt")
                        .HasColumnType("numeric");

                    b.HasKey("Bill_ID");

                    b.HasIndex("IDNo");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("EPortalApi.Models.BillService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Bill_ID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<int>("SID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Bill_ID");

                    b.HasIndex("SID");

                    b.ToTable("BillServices");
                });

            modelBuilder.Entity("EPortalApi.Models.Citizen", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IDNo"));

                    b.Property<string>("Bday")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("House_no")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phno")
                        .HasColumnType("text");

                    b.Property<string>("Street_no_name")
                        .HasColumnType("text");

                    b.HasKey("IDNo");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Citizen");
                });

            modelBuilder.Entity("EPortalApi.Models.Complaint", b =>
                {
                    b.Property<int>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("CID"));

                    b.Property<DateTime>("C_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("C_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DNo")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EID")
                        .HasColumnType("integer");

                    b.Property<int>("IDNo")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ProofImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CID");

                    b.HasIndex("DNo");

                    b.HasIndex("EID");

                    b.HasIndex("IDNo");

                    b.ToTable("Complaint");
                });

            modelBuilder.Entity("EPortalApi.Models.Department", b =>
                {
                    b.Property<int>("DNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("DNo"));

                    b.Property<string>("DName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DNo");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("EPortalApi.Models.Employee", b =>
                {
                    b.Property<int>("EID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("EID"));

                    b.Property<int>("DNo")
                        .HasColumnType("integer");

                    b.Property<string>("EAdd")
                        .HasColumnType("text");

                    b.Property<string>("EName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phno")
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.HasKey("EID");

                    b.HasIndex("DNo");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("EPortalApi.Models.Feedback", b =>
                {
                    b.Property<int>("FID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("FID"));

                    b.Property<int?>("CID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IDNo")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("WorkDoneDescription")
                        .HasColumnType("text");

                    b.HasKey("FID");

                    b.HasIndex("CID");

                    b.HasIndex("IDNo");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("EPortalApi.Models.Service", b =>
                {
                    b.Property<int>("SID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("SID"));

                    b.Property<int?>("DNo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<string>("RequiredDocs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SID");

                    b.HasIndex("DNo");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("EPortalApi.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("Bill_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentUrls")
                        .HasColumnType("text");

                    b.Property<int>("IDNo")
                        .HasColumnType("integer");

                    b.Property<int>("SID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Bill_ID")
                        .IsUnique();

                    b.HasIndex("IDNo");

                    b.HasIndex("SID");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("EPortalApi.Models.Bill", b =>
                {
                    b.HasOne("EPortalApi.Models.Citizen", "Citizen")
                        .WithMany("Bills")
                        .HasForeignKey("IDNo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("EPortalApi.Models.BillService", b =>
                {
                    b.HasOne("EPortalApi.Models.Bill", "Bill")
                        .WithMany("BillServices")
                        .HasForeignKey("Bill_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EPortalApi.Models.Service", "Service")
                        .WithMany("BillServices")
                        .HasForeignKey("SID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EPortalApi.Models.Complaint", b =>
                {
                    b.HasOne("EPortalApi.Models.Department", "Department")
                        .WithMany("Complaints")
                        .HasForeignKey("DNo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EPortalApi.Models.Employee", "Employee")
                        .WithMany("Complaints")
                        .HasForeignKey("EID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EPortalApi.Models.Citizen", "Citizen")
                        .WithMany("Complaints")
                        .HasForeignKey("IDNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EPortalApi.Models.Employee", b =>
                {
                    b.HasOne("EPortalApi.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EPortalApi.Models.Feedback", b =>
                {
                    b.HasOne("EPortalApi.Models.Complaint", "Complaint")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EPortalApi.Models.Citizen", "Citizen")
                        .WithMany("Feedbacks")
                        .HasForeignKey("IDNo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Citizen");

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("EPortalApi.Models.Service", b =>
                {
                    b.HasOne("EPortalApi.Models.Department", "Department")
                        .WithMany("Services")
                        .HasForeignKey("DNo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EPortalApi.Models.ServiceRequest", b =>
                {
                    b.HasOne("EPortalApi.Models.Bill", "Bill")
                        .WithOne("ServiceRequest")
                        .HasForeignKey("EPortalApi.Models.ServiceRequest", "Bill_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EPortalApi.Models.Citizen", "Citizen")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("IDNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EPortalApi.Models.Service", "Service")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("SID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Citizen");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EPortalApi.Models.Bill", b =>
                {
                    b.Navigation("BillServices");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("EPortalApi.Models.Citizen", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Complaints");

                    b.Navigation("Feedbacks");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("EPortalApi.Models.Complaint", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("EPortalApi.Models.Department", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Employees");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("EPortalApi.Models.Employee", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("EPortalApi.Models.Service", b =>
                {
                    b.Navigation("BillServices");

                    b.Navigation("ServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
